<a href="https://colab.research.google.com/github/UrmilaAirsang/Pytorch/blob/main/01_Pytorch_Forward_BackwardFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#from __future__ import print_function
import torch
#import torch.nn as nn
#import torch.nn.functional as F
#import torch.optim as optim
#from torchvision import datasets, transforms

In [2]:
x= torch.randn([20,1], requires_grad=True)
y= 3*x-2
print(x)
print(y)

tensor([[ 0.2921],
        [ 0.1406],
        [-0.1908],
        [ 1.1231],
        [ 1.5459],
        [-0.4909],
        [ 0.0226],
        [-0.0819],
        [-1.5020],
        [-0.4192],
        [ 0.5904],
        [ 0.0977],
        [ 1.0778],
        [-1.1043],
        [-0.6109],
        [-1.0140],
        [-1.5152],
        [ 0.0084],
        [ 0.3314],
        [ 0.5202]], requires_grad=True)
tensor([[-1.1238],
        [-1.5783],
        [-2.5725],
        [ 1.3694],
        [ 2.6377],
        [-3.4727],
        [-1.9323],
        [-2.2457],
        [-6.5061],
        [-3.2575],
        [-0.2289],
        [-1.7070],
        [ 1.2334],
        [-5.3130],
        [-3.8326],
        [-5.0419],
        [-6.5456],
        [-1.9747],
        [-1.0059],
        [-0.4395]], grad_fn=<SubBackward0>)


In [3]:
w=torch.tensor([1.], requires_grad=True)
b=torch.tensor([1.], requires_grad=True)
#print(w.item(),b.item())
y_hat = w*x+b;
# print(y_hat)
# diff = y_hat-y
# print(diff)
loss=torch.sum((y_hat-y)**2)
#print(loss)
loss.backward()

In [4]:

print(w.grad,b.grad)

tensor([-60.2338]) tensor([124.7168])
